# Project information
site_name: Application for perception camera
site_url: https://ouxt-polaris.github.io/perception_camera_app/
site_author: Sanada Tatsuya
site_description: ''
copyright: Copyright &copy; 2021 - OUXT Polaris

# Repository
repo_name: OUXT-Polaris/perception_camera_app
repo_url: https://github.com/OUXT-Polaris/perception_camera_app
edit_uri: ''
docs_dir: docs

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - toc.integrate
    #- header.autohide
  palette:
    scheme: default
  font:
    text: Roboto
    code: Roboto Mono
  favicon: images/favicon.png
  icon:
    logo: fontawesome/solid/robot
    repo: fontawesome/brands/github

# Plugins
plugins: 
  - search
  - mermaid2:
      arguments:
        theme: base
        themeVariables:
          fontFamily: verdana
          fontSize: 12px
          darkMode: false
          background: "#fff"
          primaryColor: "#DEDFEF"
          #secondaryColor: "#000"
          #mainBkg: "#0000"  # affect node bkg
          nodeBorder: "#000"
          clusterBkg: "#fff"
          clusterBorder: "#000"
          #titleColor: "#808080"
          edgeLabelBackground: "#eee"
        logLevel: 5
        securityLevel: loose
        startOnLoad: true
        arrowMarkerAbsolute: false
        flowchart:
          diagramPadding: 8
          nodeSpacing: 50
          rankSpacing: 50
          useMaxWidth: false

# Customization
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/OUXT_Polaris
    - icon: fontawesome/solid/paper-plane
      link: mailto:<ouxt.polaris.robotx@gmail.com>

extra_css:
  - stylesheets/extra.css
  # - https://raw.githubusercontent.com/OUXT-Polaris/website_resources/master/stylesheets/extra.css
  - https://use.fontawesome.com/releases/v5.15.0/css/all.css
  - https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css

extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js
  - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

# Extensions
markdown_extensions:
  - mdx_math:
      enable_dollar_delimiter: true
  - codehilite
  - pymdownx.highlight
  - fontawesome_markdown
  - admonition
  - footnotes
  - attr_list
  - toc:
      permalink: ⚓︎
      toc_depth: 3

nav:
  - Home: index.md